### ISSUE TITLE
BeatDetect

### ISSUE THREAD

**Issue by jzting** [ddf/minim-cpp#1]
Any plans to port the BeatDetect class?

**Comment by ddf** [comment]
Yes, eventually, I just haven't needed to use it yet.

**Comment by jzting** [comment]
Cool, thanks. I'm working on an iOS project now and would love to be able to use it!

**Comment by codyrotwein** [comment]
Any update on this?

**Comment by ddf** [comment]
Unlikely to happen any time soon.

**Comment by codyrotwein** [comment]
Would it mainly involve converting this file into objective-c?: https://github.com/ddf/Minim/blob/master/src/ddf/minim/analysis/BeatDetect.java

**Comment by ddf** [comment]
To C++ actually. And I believe the other classes it depends on have been ported already, so it should be reasonably straight-forward to do it. If you are feeling generous it'd be great if you forked minim-cpp and then sent me a pull request after porting it over.

**Comment by codyrotwein** [comment]
I'll give it a shot. If I'm successful, I'll definitely send the pull request.

**Comment by ddf** [comment]
Thanks very much!

**Comment by codyrotwein** [comment]
Along the same line, is there an easy way to get the minim library to work on Android? I wanted to test it out first on there before converting the BeatDetect library for iOS. Thanks!

**Comment by ddf** [comment]
Ah, that is a much bigger kettle of fish and one that I hope to have the time to tackle at some point. My plan had been to support it from the Java side, but that will require stripping out all references to JavaSound, which doesn't exist on Android. It might be an easier proposition to try to support it natively with the NDK, but I haven't looked closely at that so I'm not sure how easy it would be.

minim-cpp currently works on Windows, Mac, and iOS. It's not terribly difficult to integrate into a project, but because it's still essentially unreleased I haven't done any work documenting the project. Unfortunately all the projects I have used it in are private, so I don't have any good examples of integration to point you towards. :(

**Comment by codyrotwein** [comment]
So I believe I've finished converting the BeatDetect class into C++. But I'm wondering how I actually reference minim and this new BeatDetect class from my iOS code. Can you give me any pointers? I have all of minim-cpp files imported into my Xcode project and it builds successfully. Thank you.

**Comment by ddf** [comment]
It works pretty much exactly the same as the Java version. You need an instance of the Minim::AudioSystem class and then you can request an AudioOutput from that. For instance here's how I do that in one of my iOS projects:

```
extern void HandleAudioInterruption ( void *inClientData, Minim::InterruptionState inInterruptionState );

mAudioSystem = new Minim::AudioSystem( kOutputBufferSize, &HandleAudioInterruption, this );

extern void AudioRouteChangeListener( void *inClientData, AudioSessionPropertyID inID, UInt32 inPropertySize, const void *inPropertyValue );
AudioSessionAddPropertyListener(kAudioSessionProperty_AudioRouteChange, &AudioRouteChangeListener, this);

// turn off the wavetable optimisation that skips interpolation.
Minim::Wavetable::s_opt = false;

mOutput = mAudioSystem->getAudioOutput( TouchAudioFormat(2), kOutputBufferSize );
```

You may or may not need the interruption listener or route change. And mOutput is an Minim::AudioOutput. I'm not sure what you are doing beat detection on, but if it is an audio file you will need to get an AudioRecordingStream from your AudioSystem object and then make a new FilePlayer for that. You can then patch the FilePlayer to the AudioOutput and then pass the buffer() of AudioOutput to BeatDetect for analysis.

**Comment by ddf** [comment]
And the includes for the above code:

```
#include "AudioSystem.h"
#include "TouchServiceProvider.h"
#include "TouchAudioFormat.h"
#include "AudioOutput.h"
#include "Wavetable.h"
```

**Comment by codyrotwein** [comment]
Thank you. I'm getting audio from the microphone with a different library already and it comes back as (float **).
